parameters:
    pim_api.controller.rest.category.class: Pim\Bundle\ApiBundle\Controller\Rest\CategoryController
    pim_api.controller.rest.family.class: Pim\Bundle\ApiBundle\Controller\Rest\FamilyController
    pim_api.controller.rest.attribute.class: Pim\Bundle\ApiBundle\Controller\Rest\AttributeController
    pim_api.controller.rest.attribute_option.class: Pim\Bundle\ApiBundle\Controller\Rest\AttributeOptionController
    pim_api.controller.token.class: Pim\Bundle\ApiBundle\Controller\TokenController

services:
    pim_api.controller.rest.category:
        class: '%pim_api.controller.rest.category.class%'
        arguments:
            - '@pim_catalog.repository.category'
            - '@pim_serializer'
            - 'https://docs.akeneo.com/%s/reference/standard_format/other_entities.html#category'

    pim_api.controller.rest.family:
        class: '%pim_api.controller.rest.family.class%'
        arguments:
            - '@pim_catalog.repository.family'
            - '@pim_serializer'

    pim_api.controller.rest.attribute:
        class: '%pim_api.controller.rest.attribute.class%'
        arguments:
            - '@pim_catalog.repository.attribute'
            - '@pim_serializer'

    pim_api.controller.rest.attribute_option:
        class: '%pim_api.controller.rest.attribute_option.class%'
        arguments:
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.repository.attribute_option'
            - '@pim_serializer'
            - ['pim_catalog_simpleselect', 'pim_catalog_multiselect']

    pim_api.controller.token:
        scope: request
        class: '%pim_api.controller.token.class%'
        arguments:
            - '@fos_oauth_server.server'
