category:
    resource: '@PimApiBundle/Resources/config/routing/category.yml'
    prefix: /rest/v1/categories

family:
    resource: '@PimApiBundle/Resources/config/routing/family.yml'
    prefix: /rest/v1/families

attribute:
    resource: '@PimApiBundle/Resources/config/routing/attribute.yml'
    prefix: /rest/v1/attributes

fos_oauth_server_token:
    path: /oauth/v1/token
    defaults: { _controller: pim_api.controller.token:tokenAction }
    methods: [GET]
